identifier: k8w5t8o199278es5
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: k9n-dev
homeFolder: /Users/dannykoppenhagen/dev/k9n.dev
distFolder: dist/k9n-dev
outDir: /Users/dannykoppenhagen/dev/k9n.dev/dist/static/
handle404: ''
allowErrorCollect: false
