name: Build And Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: 'UA-XXXXXXXXX-X'
          replace: ${{ secrets.G_TAG_CODE }}
          include: 'src/environments/environment*' # Replace google Tag
      - run: npm config set legacy-peer-deps true
      - uses: cmgriffing/scully-gh-pages-action@c3b5b4bc440ffbdacc7e6430534ace82bd42899d
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          scully-args: --noPrompt
