name: Scully Publish

on:
  push:
    branches:
      - main
      - 'blog/**'
      - schematics-helpers

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13'
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: 'UA-XXXXXXXXX-X'
          replace: ${{ secrets.G_TAG_CODE }}
          include: 'src/environments/environment*' # Replace google Tag
      - uses: cmgriffing/scully-gh-pages-action@v9
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          build-args: --noPrompt

  sync-devto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: 'DEVTO_API_KEY'
          replace: ${{ secrets.DEVTO_API_KEY }}
          include: 'scripts/devto-update.js' # Replace with real API Key
      - run: cd scripts && npm ci && node devto-update.js
